# Generated by Django 4.1.2 on 2022-12-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_alter_transaction_transaction_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='role',
            field=models.CharField(max_length=100, null=True, verbose_name='Role'),
        ),
    ]
