# Generated by Django 4.1.3 on 2022-12-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_activity_log_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_user', models.CharField(max_length=100, verbose_name='List User')),
                ('profile_fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('profile_mname', models.CharField(max_length=100, verbose_name='Middle Name')),
                ('profile_lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('profile_cnumber', models.CharField(max_length=100, verbose_name='Contact Number')),
                ('profile_address', models.CharField(max_length=100, verbose_name='Address')),
                ('profile_email', models.CharField(max_length=100, verbose_name='Email Address')),
            ],
        ),
    ]
