# Generated by Django 4.1.3 on 2022-12-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email Address'),
        ),
    ]
