# Generated by Django 4.1.3 on 2022-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_alter_profile_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_fname',
            field=models.CharField(max_length=250, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_lname',
            field=models.CharField(max_length=250, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_mname',
            field=models.CharField(max_length=250, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='reseller_address',
            field=models.TextField(verbose_name='Address'),
        ),
    ]
