# Generated by Django 4.1.3 on 2022-12-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_remove_orderitem_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('available', 'available'), ('low stock', 'low stock'), ('n/a', 'n/a')], max_length=200, verbose_name='Status'),
        ),
    ]
