# Generated by Django 4.1.3 on 2022-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.BigIntegerField(max_length=200, verbose_name='Available Stock'),
        ),
    ]
