# Generated by Django 4.1.3 on 2022-12-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0012_alter_pos_pos_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='OrderItem_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='pos_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Price'),
        ),
    ]
