# Generated by Django 4.1.3 on 2022-12-14 05:10

import admin_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0013_alter_orderitem_orderitem_amount_alter_pos_pos_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=admin_site.models.image_path, verbose_name='Profile Pic'),
        ),
    ]
