# Generated by Django 4.1.3 on 2022-12-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0014_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cnumber',
            field=models.BigIntegerField(verbose_name='Contact Number'),
        ),
    ]
