# Generated by Django 4.1.3 on 2022-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0015_alter_profile_profile_cnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='pos_quantity',
            field=models.BigIntegerField(null=True, verbose_name='quantity'),
        ),
    ]
