# Generated by Django 4.1.2 on 2022-12-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0016_alter_pos_pos_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='pos_size',
            field=models.CharField(max_length=200, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(max_length=200, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Shipping', 'Out for Shipping'), ('Declined', 'Decline'), ('Completed', 'Completed')], default='Pending', max_length=250, null=True, verbose_name='Status'),
        ),
    ]
