# Generated by Django 4.1.2 on 2022-12-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0018_alter_transaction_transaction_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_email',
            field=models.CharField(max_length=100, verbose_name='Email Address'),
        ),
    ]
