# Generated by Django 4.1.2 on 2022-12-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0020_remove_product_product_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_batch',
            field=models.CharField(max_length=200, null=True, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_expired',
            field=models.DateField(null=True, verbose_name='Expiration Date'),
        ),
    ]
