# Generated by Django 4.1.2 on 2022-12-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0021_product_product_batch_product_product_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_size',
            new_name='product_unit',
        ),
    ]
