# Generated by Django 4.1.2 on 2022-12-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0024_by_batch_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='pos_size',
            new_name='pos_unit',
        ),
    ]
