# Generated by Django 4.1.2 on 2022-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0025_rename_pos_size_pos_pos_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='OrderItem_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='OrderItem_unit',
            field=models.CharField(max_length=200, null=True, verbose_name='Unit'),
        ),
    ]
