# Generated by Django 4.1.2 on 2023-01-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0026_remove_orderitem_orderitem_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_user', models.CharField(default=None, max_length=200, verbose_name='List user')),
                ('pos_TotalAmount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount')),
                ('pos_cash', models.CharField(default=None, max_length=200, verbose_name='Cash')),
                ('pos_change', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Change')),
            ],
        ),
    ]
