# Generated by Django 4.1.3 on 2023-01-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0027_pos_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_sales',
            name='pos_cash',
            field=models.BigIntegerField(null=True, verbose_name='Cash'),
        ),
    ]
