# Generated by Django 4.1.3 on 2023-01-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0028_alter_pos_sales_pos_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_preffered_date',
            field=models.CharField(max_length=250, null=True, verbose_name='Preffered Date'),
        ),
        migrations.AlterField(
            model_name='pos_sales',
            name='pos_user',
            field=models.CharField(default=None, max_length=200, verbose_name='Role'),
        ),
    ]
