# Generated by Django 4.1.3 on 2023-01-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0031_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('available', 'available'), ('not available', 'not available')], max_length=200, verbose_name='Status'),
        ),
    ]
