# Generated by Django 4.1.3 on 2023-01-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0035_alter_pos_sales_pos_totalamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos_sales',
            name='pos_no',
            field=models.IntegerField(null=True, verbose_name='Pos No'),
        ),
    ]
