# Generated by Django 4.1.3 on 2023-01-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0036_pos_sales_pos_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos_sales',
            name='pos_no',
        ),
    ]
