# Generated by Django 4.1.3 on 2023-01-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0037_remove_pos_sales_pos_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos_sales',
            name='pos_cash',
        ),
        migrations.RemoveField(
            model_name='pos_sales',
            name='pos_change',
        ),
        migrations.AddField(
            model_name='pos',
            name='pos_cash',
            field=models.BigIntegerField(null=True, verbose_name='Cash'),
        ),
        migrations.AddField(
            model_name='pos',
            name='pos_change',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Change'),
        ),
    ]
