# Generated by Django 4.1.3 on 2023-01-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0039_pos_payment_delete_pos_sales_remove_pos_pos_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos_payment',
            name='pos_no',
            field=models.IntegerField(null=True, verbose_name='Role'),
        ),
    ]
