# Generated by Django 4.1.3 on 2023-01-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0040_pos_payment_pos_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_payment',
            name='pos_no',
            field=models.IntegerField(null=True, verbose_name='Pos Number'),
        ),
    ]
