# Generated by Django 4.1.3 on 2023-01-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0041_alter_pos_payment_pos_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos_payment',
            name='pos_no',
        ),
        migrations.AddField(
            model_name='pos_payment',
            name='pos_status',
            field=models.CharField(choices=[('Printed', 'Printed'), ('not Print', 'not Print')], max_length=250, null=True, verbose_name='Pos Number'),
        ),
    ]
