# Generated by Django 4.1.3 on 2023-01-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0042_remove_pos_payment_pos_no_pos_payment_pos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_payment',
            name='pos_status',
            field=models.CharField(choices=[('Printed', 'Printed'), ('not Print', 'not Print')], max_length=250, null=True, verbose_name='Status'),
        ),
    ]
