# Generated by Django 4.1.3 on 2023-01-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0044_pos_payment_pos_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ResellerPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Reseller Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pos Price'),
        ),
    ]
