# Generated by Django 4.1.3 on 2023-02-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0047_pos_pos_reselleramount_alter_pos_pos_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Decline', 'Decline'), ('Completed', 'Completed')], default='Pending', max_length=250, null=True, verbose_name='Status'),
        ),
    ]
