# Generated by Django 4.1.2 on 2023-02-04 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0048_alter_transaction_transaction_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=' Date Ordered '),
        ),
    ]
