# Generated by Django 4.1.2 on 2023-02-04 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0054_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=datetime.date, verbose_name=' Date Ordered '),
        ),
    ]
