# Generated by Django 4.1.3 on 2023-02-04 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0064_pos_payment_pos_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='by_batch',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='by_batch',
            name='product_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Name'),
        ),
    ]
