# Generated by Django 4.1.3 on 2023-02-04 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0065_by_batch_created_at_by_batch_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='by_batch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
